# https://travis-ci.org/tgbugs/pyontutils
sudo: false
language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6

install:
  - pip install pipenv
  - pip install coverage coveralls nose-timer && export HAS_COVERALLS=1
  - pipenv install --dev --system --skip-lock

script:
  - pipenv run nosetests --verbose --with-coverage --cover-tests --cover-package=pyontutils

after_success:
  - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi
